### ISSUE TITLE
[疑問] Session 登出後，點擊選單，iframe 內容出現登入畫面

### ISSUE THREAD

**Issue by ft525** [ichynul/iframe-tabs#12]
如題
如果 Session 在另一個瀏覽器分頁被登出後，在原本分頁裡點擊選單，iframe 內容會出現登入畫面，
理論上應該要是全螢幕方式呈現，而不是用 iframe-tabs 方式
但是在 iframe 裡實際登入後又會是正常的

請問這樣是否正常？

**Comment by ichynul** [comment]
这个问题以前也多次提过，在最近几个版本已经改进了，就是如果某个iframe跳转登录页面，会刷新框架顶级主体，这样主体就会跳转登录。
配置里面要打开`'force_login_in_top' => true`。//没有这个配置默认也为 `true`
目前来说勉强可以实现需求，唯一不足的是iframe先进入login，然后顶级页面才进入login，会有点延迟。
其他方法暂时没想到， 顶级页面定时器轮询登录状态的方案也曾想过，不好实现。
不知道你现在使用的是不是最新版本。

**Comment by ft525** [comment]
我目前都是用最新版本的測試

其出現在 iframe 裡的登入頁，重新登入後，就會恢復正常
只不過正常來講 login 頁面應該出現在 top，而感到疑問而已
