### ISSUE TITLE
现在版本怎么都乱了，是不是测试代码上传了

### ISSUE THREAD

**Issue by Wong-Dy** [ichynul/iframe-tabs#13]
如题
更新之后 右边内容header样式错乱

**Comment by ichynul** [comment]
布局有改动，需要更新一下样式资源。
执行一下：`php artisan vendor:publish --tag=iframe-tabs --force`

**Comment by Wong-Dy** [comment]
执行了还是一样哎。

**Comment by ichynul** [comment]
会不会是视图缓存的原因，你把`/storage/framework/views`缓存里面的都删了试试

**Comment by Wong-Dy** [comment]
删了也不行，header上面多了一层：
<div class="content-tabs" style="width: 804px;">
    <nav class="page-tabs menuTabs tab-ui-menu" id="tab-menu">
        <div class="page-tabs-content" style="margin-left: 0px;">
        <a href="javascript:void(0);" data-pageid="_admin_dashboard" class="menu_tab active"><span class="page_tab_title"><i class="fa fa-home"></i>Home</span></a></div>
    </nav>
    <div class="content-tabs-divider" style="background-color: rgb(96, 92, 168);"></div>
</div>

**Comment by Wong-Dy** [comment]
<div class="content-tabs" style="width: 804px;">
    <nav class="page-tabs menuTabs tab-ui-menu" id="tab-menu">
        <div class="page-tabs-content" style="margin-left: 0px;">
        <a href="javascript:void(0);" data-pageid="_admin_dashboard" class="menu_tab active"><span class="page_tab_title"><i class="fa fa-home"></i>Home</span></a></div>
    </nav>
    <div class="content-tabs-divider" style="background-color: rgb(96, 92, 168);"></div>
</div>

**Comment by Wong-Dy** [comment]
```
<div class="content-tabs" style="width: 804px;">
    <nav class="page-tabs menuTabs tab-ui-menu" id="tab-menu">
        <div class="page-tabs-content" style="margin-left: 0px;">
        <a href="javascript:void(0);" data-pageid="_admin_dashboard" class="menu_tab active"><span class="page_tab_title"><i class="fa fa-home"></i>Home</span></a></div>
    </nav>
    <div class="content-tabs-divider" style="background-color: rgb(96, 92, 168);"></div>
</div>
```

**Comment by ichynul** [comment]
就是布局变了，tab移到header里面了，问题是你的样式还是旧的。
你打开你本地的`public\vendor\laravel-admin-ext\iframe-tabs\dashboard.css`和仓库里面比较一下。
我觉得可能是资源css资源更新没成功，我上面给出的命令后面有`--force`，不带的话就覆盖不了。
还有可能就是你执行命令的路径错了，没在网站根目录。
你再试一下，我公司和家里面的系统都用这套的，没发现这个问题。

**Comment by ichynul** [comment]
![2019-04-16T10-38-15 736Z](https://user-images.githubusercontent.com/10061650/56203023-ed96c800-6076-11e9-9ffb-15ca25f51cd5.png)

**Comment by Wong-Dy** [comment]
dashboard.css确实不一样，之前我把依赖重新装了，资源文件也删了，重新安装了一遍还是一样的，不清楚怎么回事
