### ISSUE TITLE
普通角色打开不正常

### ISSUE THREAD

**Issue by xuanyanwow** [ichynul/iframe-tabs#15]
普通角色打开后，无tab列表，左上角的登录都不见了，用超级管理员账号登录能正常

如果给普通角色权限 admin/* 全部权限，也能正常。请问作者知道是怎么回事吗 

![image](https://user-images.githubusercontent.com/28777109/56467389-da0da780-6450-11e9-906b-3b3c91e66ed5.png)

**Comment by ichynul** [comment]
权限没分配到，`Tab-dashboard`这个权限分配给那个普通用户。
![20190421162421](https://user-images.githubusercontent.com/10061650/56467482-f827d780-6451-11e9-9c56-b08cbe7d5314.png)

**Comment by xuanyanwow** [comment]
你好，权限我已经分配了的，除了系统默认第一个权限，`admin/*`   其他我添加的都已经赋予

角色权限分配 

![image](https://user-images.githubusercontent.com/28777109/56467559-1a6e2500-6453-11e9-83bc-64711e857af4.png)


测试用户所属角色

![image](https://user-images.githubusercontent.com/28777109/56467569-35d93000-6453-11e9-9407-040cb66a451c.png)

**Comment by xuanyanwow** [comment]
因为第一次接触该扩展，所以无法确定是我的问题还是有未知bug，可以的话希望能提供排查思路 ，我进一步测试。谢谢

**Comment by ichynul** [comment]
再分一个主体框架的权限给他:
![20190421164738](https://user-images.githubusercontent.com/10061650/56467718-4b4f5980-6455-11e9-9455-70d1dab5d46e.png)

**Comment by xuanyanwow** [comment]
手动添加该权限后正常！谢谢。
