### ISSUE TITLE
现在刷新页面会回到首页,怎么可以留在当前页面呢?

### ISSUE THREAD

**Issue by never615** [ichynul/iframe-tabs#17]

**Comment by ichynul** [comment]
不太明白你说的意思，你刷新的是什么页面？

**Comment by never615** [comment]
就是我点左侧菜单,右边会显示对应的模块.
这个时候,刷新页面,右边的模块就会变成默认的.

因为引入这个库之后,页面的url不会随着我点左侧菜单而变化了.

**Comment by ichynul** [comment]
就好比一个操作系统上面运行了很多程序，刷新页面就像重启电脑一样，运行的程序都不在了。
一般情况下是不刷新主体页面的，哪个模块需要刷新就单独的刷新它

**Comment by never615** [comment]
我理解这个....就是顾客使用浏览器的习惯,可能有事没事f5一下....🤣
