### ISSUE TITLE
session过期，刷新页面（页签操作-》刷新当前），还会出现退出页面在tab页里显示的问题

### ISSUE THREAD

**Issue by lychuan** [ichynul/iframe-tabs#2]
当session过期，点击 “页签操作”里面的“刷新当前”，还是会出现退出页面在tab页里显示的问题，不过刷新浏览器是正常的。

**Comment by lychuan** [comment]
当session过期，点击左右导航菜单，退出页面也会在tab页里显示，正常感觉也应该在上一层显示。。。

**Comment by ichynul** [comment]
右上角个人信息的两个按钮【设置】【登出】，【设置】点击在tab里面打开并关闭个人信息弹出区域，【登出】会在最上层退出跳转到登录界面，这个应该没问题吧。
至于tab里面session过期刷会跳转登录，每个人看法不同。我觉得这样也行的，可能他还有很多tab页面同时打开的，他在其中一个tab登录刷新了状态，其他的tab就可以继续使用了。要让最顶层跳转登录，顶层搞个定时轮询检测状态或者检测iframe的url变化。
```php
//app/Admin/bootstrap.php
if (\Request::route()->getName() == 'iframes.index') {//当前页面是最顶层
    Admin::js('/vendor/js/xxxxx.js');//加载js,在js里面写监听逻辑。
} 
```

**Comment by ichynul** [comment]
最近在研究这个问题，发现比想象中难弄。轮询的办法好像行不通，因为轮询的时候会刷新登录的session状态。

**Comment by ichynul** [comment]
新版本可以了，加上配置参数`'force_login_in_top' => true`
