### ISSUE TITLE
v1.1.12 有bug

### ISSUE THREAD

**Issue by mobileliker** [ichynul/iframe-tabs#20]
升级成v1.1.12之后，顶部的tab项会被顶到下一行，如图：

[截图](https://s2.ax1x.com/2019/05/11/EWHKgJ.png)

查明原因为 resources/view/ext/index.blade.php 第146行设置了width为100%导致换行，望能测试一下是否有这个问题
```
        $('.content-tabs').css({
            'left': window.tabs_left + 'px',
            'width': '100%'
        });
```

**Comment by ichynul** [comment]
那你升级前版本号是多少？
不一定是v1.1.12 大问题，可能你在升级前已经更新了多个版本。
你执行命令重新强制发布一下资源看看：`php artisan vendor:publish --tag=iframe-tabs --force`
