### ISSUE TITLE
side bar issue

### ISSUE THREAD

**Issue by demdaysao** [ichynul/iframe-tabs#21]
can't scroll up the sidebar to access the overflow menu items

**Comment by ichynul** [comment]
Do you mean the left menus , or the top tab menus.
If left menus , dissable this extension and check wether it is OK.
```php
 'iframe-tabs' => [
            // Set to `false` if you want to disable this extension
            'enable' => true,
]
```
If the top tab menus , force release resources and try again .
`php artisan vendor:publish --tag=iframe-tabs --force`

**Comment by demdaysao** [comment]
I mean left menu, it's ok if I disable the extension but can't scroll the left menu when enable the extension. My left menu have more than 20 item groups but can't access the last group becoz it overflow and can't scroll.

**Comment by ichynul** [comment]
I can't reproduce this problem. Maybe something else caused it.
