### ISSUE TITLE
点击编辑或者查看都会打开一个新页面？

### ISSUE THREAD

**Issue by Wong-Dy** [ichynul/iframe-tabs#22]
不知道是问题还是新加的功能？
个人感觉体验不怎么好啊，可以无限打开新页面，比如点击编辑->新页面->列表->编辑->新页面...

**Comment by ichynul** [comment]
扩展设置里面修改：
`'bind_urls' => 'none',`
这是新加的功能，点击grid列表页a标签会以弹出[popup]或新tab[new_atb]方式打开。
当然，这两种方式都需要调整一下，把form/detail里面的list/edit/view之类的隐藏掉。
