### ISSUE TITLE
点击刷新显示代码BUG反馈

### ISSUE THREAD

**Issue by taobali32** [ichynul/iframe-tabs#23]
环境:window10 + Laragon + php7.1 
当点击 右侧头像旁边的  刷新按钮时
`<a href="javascript:void(0);" class="container-refresh">
      <i class="fa fa-refresh"></i>
 </a>`

会出现
'; $('.tab-content').append(html); return 1; }, close: function(index) { $('.tab-content .loading-message').remove(); }, open: function() { alert('layer.js dose not work.'); } }; } $('body').on('click', '#tab-menu a.menu_tab', function() { var pageId = getPageId(this); var $ele = null; $(".sidebar-menu li a").each(function() { var $meun = $(this); if ($meun.attr('data-pageid') == pageId) { $ele = $meun; return false; //退出循环 } }); if ($ele) { $ele.parents('.treeview').not('.active').find('> a').trigger('click'); setTimeout(function() { var $parent = $ele.parent().addClass('active'); $parent.siblings('.treeview.active').removeClass('active'); $parent.siblings().removeClass('active').find('li').removeClass('active') }, 500); } }); $('body').on('click', '.sidebar-menu li a,.navbar-nav>li a,.sidebar .user-panel a,.sidebar-form .dropdown-menu li a', function() { var url = $(this).attr('href'); if (!url || url == '#' || /^javascript|\(|\)/i.test(url)) { return; } if ($(this).attr('target') == '_blank') { return; } if ($(this).hasClass('iframes-pass-url')) { return; } if (window.pass_urls) { for (var i in window.pass_urls) { if (url.indexOf(window.pass_urls[i]) > -1) { return true; } } } var icon = ''; if ($(this).find('i.fa').size()) { icon = $(this).find('i.fa').prop("outerHTML"); } var span = $(this).find('span'); var id = url == window.home_uri ? '_admin_dashboard' : url.replace(/\W/g, '_'); addTabs({ id: id, title: span.size() ? span.text() : $(this).text().length ? $(this).text() : '*', close: true, url: url, urlType: 'absolute', icon: icon }); $(this).attr('data-pageid', id); var toggle = false; if ($(this).parents('.dropdown').size() && (toggle = $(this).parents('.dropdown').find('.dropdown-toggle'))) { toggle.trigger('click'); } if ($(this).parents('.sidebar-form') && (toggle = $(this).parents('.sidebar-form').find('.input-group-btn button'))) { toggle.trigger('click'); } return false; }); if (window == top) { addTabs({ id: '_admin_dashboard', title: window.home_title, close: false, url: window.home_uri, urlType: 'absolute', icon: '' }); } else { if (location.href == window.iframes_index) { location.href = window.home_uri; $('body').html('....'); } } $('body').on('click', '.main-header a.logo', function() { return false; }); $('.navbar-custom-menu').css('background-color', $('.main-header .navbar').css('background-color')); $('.navbar-custom-menu').show(); // delete it in future if (!$(".navbar-custom-menu>ul>*:first").hasClass('tab-options')) { $(".navbar-custom-menu>ul>*:first").before($('.navbar-custom-menu>ul>li.tab-options')); } $('.content-tabs').css({ 'left': window.tabs_left + 'px', 'width': '100%' }); });

ncaught SyntaxError: Invalid or unexpected token
暂未找到解决方法

**Comment by ichynul** [comment]
已做了修复，升级到最新版

**Comment by taobali32** [comment]
> 已做了修复，升级到最新版

谢谢大佬，可以给我下解决思路吗，  
ncaught SyntaxError: Invalid or unexpected token  追了下js 到这行并没有token什么的， 只有一个if判断，对pajx不太熟悉

**Comment by ichynul** [comment]
你说的这个就是上面那个问题吗，还是一个新的问题？

**Comment by taobali32** [comment]
> 你说的这个就是上面那个问题吗，还是一个新的问题？

上面的问题，

但是 又发现一个新的 问题， 在用户体验方面，

layui的弹窗和一个其他包(点击放大图片包)冲突了

扩展包地址：
https://github.com/laravel-admin-extensions/grid-lightbox
composer require laravel-admin-ext/grid-lightbox


使用方式:
`  $grid->picture('avatar')->display(function ($avatar) {
                return 'http://f.hiphotos.baidu.com/image/pic/item/8d5494eef01f3a29f863534d9725bc315d607c8e.jpg';
            })->lightbox(['width' => 50, 'height' => 50]);`


这个包的目的是在数据表格中点击图片放大，
现在会出现的结果是 弹出一个层显示图片， 关闭这个弹层就会显示这个包应有的功能

**Comment by ichynul** [comment]
这个问题是以为tabel里面的a标签都被绑定了点击事件，新版本加强了限制，只对表格最后一列的eidt和view绑定点击

**Comment by taobali32** [comment]
> 这个问题是以为tabel里面的a标签都被绑定了点击事件，新版本加强了限制，只对表格最后一列的eidt和view绑定点击

谢谢你
