### ISSUE TITLE
页面右侧点击  关闭其他页面没有反应

### ISSUE THREAD

**Issue by taobali32** [ichynul/iframe-tabs#24]
关闭当前,关闭全部,关闭其他点击没有反应.    我的邮箱 :3196672779@qq.com,  大佬,如果可以,   可以加下qq好友吗,  我正在用这个 iframe扩展,  期间问题有点多. 希望可以得到大佬的帮助

**Comment by ichynul** [comment]
执行一下：
`php artisan vendor:publish --tag=iframe-tabs --force`
看还有问题吗
