### ISSUE TITLE
使用hhxsv5/laravel-s后台问题

### ISSUE THREAD

**Issue by ashuiccc** [ichynul/iframe-tabs#25]
想配合使用[swoole](https://github.com/hhxsv5/laravel-s/blob/master/README-CN.md#与nginx配合使用推荐) ,后台打开后成这个样子

<img width="1678" alt="QQ20190805-111251@2x" src="https://user-images.githubusercontent.com/50192266/62436361-fd473300-b771-11e9-82cf-66f0e24697a4.png">

**Comment by ichynul** [comment]
那你使用这个之前是正常的吗？

**Comment by ashuiccc** [comment]
> 那你使用这个之前是正常的吗？

enable=false后 界面显示正常

**Comment by ichynul** [comment]
这个东西我没用过，不好推测是哪里的问题，最近还有点忙碌。
确认一下首页这个菜单指向的链接对不对：
![图片](https://user-images.githubusercontent.com/10061650/62635556-7e691a80-b96a-11e9-8961-717c6c614209.png)
在浏览器里面审查看看是不是分左右结构，右边有没有iframe。
看看浏览器控制台有没有报什么js错误。
如果可以的话，在保持本扩展打开的情况下，切换你使用的[hhxsv5/laravel-s]，使用或不使用，看有没有不同。

**Comment by ichynul** [comment]
最新版本已修复此问题，升级到最新版，在扩展配置里面新加配置：`'web_in_cli' => false`
