### ISSUE TITLE
我根据laravel-admin的扩展文档安装了iframe-tabs,结果后台左侧菜单和顶部都消失了。求解。

### ISSUE THREAD

**Issue by qingliangguo123** [ichynul/iframe-tabs#26]
安装好以后，左侧的菜单和顶部的导航都消失了。怎么回事呢？求大神解答。

**Comment by ichynul** [comment]
下面两个命令执行了吗？
···
$ php artisan vendor:publish --tag=iframe-tabs

$ php artisan admin:import iframe-tabs
····

**Comment by qingliangguo123** [comment]
执行了。

**Comment by qingliangguo123** [comment]
-->php artisan vendor:publish --tag=iframe-
tabs
Copied Directory [\vendor\ichynul\iframe-tabs\resources\assets] To [\public\vend
or\laravel-admin-ext\iframe-tabs]
Publishing complete.

-->php artisan admin:import iframe-tabs
Extension [Ichynul\IframeTabs\IframeTabs] imported

这是执行结果。。。
