### ISSUE TITLE
laravel5.6执行命令报错

### ISSUE THREAD

**Issue by phpyii** [ichynul/iframe-tabs#3]
laravel:5.6.33
laravel-admin:1.6.9
iframe-tabs:1.0.17

执行php artisan admin:import iframe-tabs报错
`Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string`

**Comment by ichynul** [comment]
我试了没发现你的这个问题，可能是你代码里有什么问题。这个命令很简单，创建一个菜单权限，其他都没有涉及。有问题的话是重复执行此命令导入会报错，因为重复创建权限，触发了权限表Permission的唯一约束。
