### ISSUE TITLE
左邊選單太長會無法捲動

### ISSUE THREAD

**Issue by ft525** [ichynul/iframe-tabs#32]
如題，左邊選單內容太長，會被遮住看不到，無法捲動

我有在 aside.main-sidebar 加上這 2 個 css 就可以了 {
    height: 100%;
    overflow-y: auto;
}

我的 Laravel-admin 版本是 1.6.11

**Comment by ichynul** [comment]
这个问题好几个人提到了，但我测试不出来。实际使用中没有遇到菜单太多的情况，通过浏览器查看元素，复制节点测试。
它左边菜单有个[slimScrollDiv]来处理滚动的，不清楚为什么会有滚动问题，先按你的解决方法来吧。
