### ISSUE TITLE
新版本更新以后，footer没了，窄边导航的时候鼠标移上去不弹出菜单了。

### ISSUE THREAD

**Issue by Yesr00** [ichynul/iframe-tabs#35]
![image](https://user-images.githubusercontent.com/47804568/68110244-80ba2100-ff27-11e9-91ed-8b3cf24bdde7.png)

如上图所示，原本鼠标移上去应该有菜单显示出来。现在移上去是没有反应的。

**Comment by ichynul** [comment]
你执行命令更新一下资源看看，`php artisan vendor:publish --tag=iframe-tabs --force`，我这里测试了没问题，开始我以为是今天改动的出问题了。

**Comment by Yesr00** [comment]
![image](https://user-images.githubusercontent.com/47804568/68124613-c2a88e80-ff4a-11e9-8ac8-38acbc2e0fb2.png)
执行完以后。footer依然不行，本地的窄边栏倒是可以了。不过线上好像还不行。难道是因为我composer用的阿里镜像更新慢了？=，=|||

**Comment by ichynul** [comment]
顶级页面有header没有footer，每个iframe没有header有footer，一直都是如此。就是说右边区域每个页面都有一个footer的，你的是全部都没有footer吗，还是某个页面没有？

**Comment by Yesr00** [comment]
所有的页面都没有footer

**Comment by vonsogt** [comment]
Check mine that's work for side menu, but some kinda bug on the side menu too
https://imgur.com/a/tkEpLzi

and this is related to issue #36

**Comment by ichynul** [comment]
布局的问题，`/config/admin.php`: 'layout'里面最好有个 `fixed`,新版本会自动加上。

**Comment by vonsogt** [comment]
layout `'sidebar-mini'` not showing the mini icon on the side menu.
![image](https://user-images.githubusercontent.com/35516476/68183736-d2b68180-ffcf-11e9-9141-d825607d946e.png)
and the code forced to be fixed at this line
https://github.com/ichynul/iframe-tabs/commit/bbe7b6b6e2b37387de33a57be4d54d00736396ae#diff-9957ee2fe6810d62675d3c3e4fa20abaR100


and the scroll bar still visible:
![image](https://user-images.githubusercontent.com/35516476/68183527-4ad07780-ffcf-11e9-9245-8b4b8eec901b.png)

not like this when I tried to deactivate the extension:
![image](https://user-images.githubusercontent.com/35516476/68183878-2759fc80-ffd0-11e9-93a9-e2c394445667.png)

**Comment by vonsogt** [comment]
Now it works at version 1.2.35, nice job @ichynul 
Thank you very much

**Comment by Yesr00** [comment]
升级1.2.35 问题已解决。。。
