### ISSUE TITLE
安装后报错：Undefined variable: _user_ 

### ISSUE THREAD

**Issue by Ace520** [ichynul/iframe-tabs#38]
`
Facade\Ignition\Exceptions\ViewException
Undefined variable: _user_ (View: /mnt/hgfs/E/php/laravel/vendor/encore/laravel-admin/resources/views/index.blade.php)
`

**Comment by ichynul** [comment]
这个可能是laravel-admin的问题，先观察一下吧

**Comment by Ace520** [comment]
已处理，版本问题
