### ISSUE TITLE
菜单显示问题

### ISSUE THREAD

**Issue by pramy-yang** [ichynul/iframe-tabs#39]
后台正上方操作菜单,屏幕稍微小一点菜单就隐藏了(f12调试往左边稍微一拉),希望能修复一下

**Comment by ichynul** [comment]
`php artisan vendor:publish --tag=iframe-tabs --force`
更新一下样式看看

**Comment by pramy-yang** [comment]
> `php artisan vendor:publish --tag=iframe-tabs --force`
> 更新一下样式看看

我今天刚装的扩展 之前没在这个项目中用过

**Comment by pramy-yang** [comment]
> `php artisan vendor:publish --tag=iframe-tabs --force`
> 更新一下样式看看

明天去试一下

**Comment by pramy-yang** [comment]
> `php artisan vendor:publish --tag=iframe-tabs --force`
> 更新一下样式看看

还是一样

**Comment by ichynul** [comment]
https://github.com/ichynul/iframe-tabs/blob/85940802e18fc1581c94664b96cc8816e7fcd3c8/resources/assets/dashboard.css#L236
菜单在小屏幕尺寸下错位的问题之前已经修复过。
不太确定你说的是不是这个问题，你能截个图看看吗？

**Comment by pramy-yang** [comment]
> https://github.com/ichynul/iframe-tabs/blob/85940802e18fc1581c94664b96cc8816e7fcd3c8/resources/assets/dashboard.css#L236
> 
> 
> 菜单在小屏幕尺寸下错位的问题之前已经修复过。
> 不太确定你说的是不是这个问题，你能截个图看看吗？

github图片传不了,昨天也不能上传,不是菜单错误,是中等以下的屏幕尺寸,正上方的菜单由于响应式原因,全部隐藏掉了,全屏的话菜单就是一块一块的正常显示

**Comment by ichynul** [comment]
已经修改了，更新到最新版，
执行 `php artisan vendor:publish --tag=iframe-tabs --force` 发布一下资源

**Comment by pramy-yang** [comment]
> 已经修改了，更新到最新版，
> 执行 `php artisan vendor:publish --tag=iframe-tabs --force` 发布一下资源

好的 已经好了 谢谢
