### ISSUE TITLE
安装之后菜单栏都不显示了

### ISSUE THREAD

**Issue by Sentiger** [ichynul/iframe-tabs#4]
根据文档步骤，安装之后左边菜单栏不显示了
[
    'title'     => 'Index',
    'icon'      => 'fa-bar-chart',
    //'uri'       => '/', //old
    'uri'       => '/admin/dashboard',   // new
]这个配置在哪里配置

**Comment by ichynul** [comment]
打开`http://host/admin`是主页面，其他的页面都是iframe子页面，子页面不显示菜单之类的。
那个配置是要修改一下菜单，第一个　首页指向`/admin` ,修改指向为`/admin/dashboard`。因为/admin已经作为主页面了。要另外指定一个默认起始页面。
