### ISSUE TITLE
出现 错误Possible typo $_user_ Did you mean $use_icon?

### ISSUE THREAD

**Issue by 365556520** [ichynul/iframe-tabs#40]
Possible typo $_user_
Did you mean $use_icon?

**Comment by 365556520** [comment]
然后整个网站都进不去了

**Comment by ichynul** [comment]
这个问题以前有人提过了，开始我以为是laravel-admin的问题，今天认真的看了一下，确实是这个扩展跟它新的改动不兼容。
已经修复了，你更新一下看看。
