### ISSUE TITLE
在当前tab里点击链接，比如首页上点击，能不能新增一个对应tab而不是在当前页打开？

### ISSUE THREAD

**Issue by Yesr00** [ichynul/iframe-tabs#41]
![image](https://user-images.githubusercontent.com/47804568/70195428-9d24c580-1740-11ea-81f4-96faf7a8d613.png)
![image](https://user-images.githubusercontent.com/47804568/70195486-d2311800-1740-11ea-9f3e-fa0724534a82.png)

**Comment by ichynul** [comment]
`top.openPop(url, title, area);`//新弹出框(顶层)
`window.openPop(url, title, area);`(当前窗口)
`top.openTab(url, title, icon);//`新选项卡

https://github.com/ichynul/iframe-tabs/blob/fb231896baa218a2da01d036c835a54ec91fd9cf/resources/views/index/content.blade.php#L50

**Comment by Yesr00** [comment]
好的，我试试，谢谢大佬。。。在InfoBox里好像没法子

**Comment by Yesr00** [comment]
搞定了。InfoBox里链接使用 “JavaScript:top.openTop('url')”  就可以了。。。
