### ISSUE TITLE
登录后跳转回登录前浏览的页面 消失 ！！！

### ISSUE THREAD

**Issue by yikaiba** [ichynul/iframe-tabs#45]
如题，怎样设置可以 登录后跳转回登录前浏览的页面 呢？

**Comment by ichynul** [comment]
这感觉有点难实现，默认是任何一个页面超时了，都会整体跳转登录页面。
你可以设置`force_login_in_top` 为 `false`，这样某个选项卡页面触发超时，只会在那个页面跳转登录，最大程度的保留其余页面打开状态。
