### ISSUE TITLE
关于刷新和关闭当前top.openPop

### ISSUE THREAD

**Issue by Yesr00** [ichynul/iframe-tabs#46]
如题。当前使用 parent.layer.closeAll()会关闭所有的top.openPop窗口。有没有办法只关闭当前操作的窗口？同理求教刷新当前弹窗的问题。使用window.reload()会全局刷新。

**Comment by ichynul** [comment]
openPop方法把layer 的index返回给你，用`top.layer.close(index)`，这样可以吧。
或者你自己封装一个`top.layer.open()`。

**Comment by Yesr00** [comment]
大佬。Laravel-Admin更新以后。content.blade.php好像跟原本的有冲突。不删掉报content未定义，删掉的话更新完插件报_view_未定义。。。是兼容性的问题么。。。
![image](https://user-images.githubusercontent.com/47804568/77812375-df9d5400-70db-11ea-9590-ae87231f0ab5.png)

**Comment by ichynul** [comment]
我这里测试了是正常的，laravel-admin:1.7.14，laravel/framework:5.6.*。

**Comment by Yesr00** [comment]
Emmmm...我重新composer update 又可以了。。。然后是昨晚大佬给的那个top.layer.close(index)的方法。。。我是在Laravel-Admin控制器的Form里做了个保存回调。回调后执行关闭openPop.这个时候index好像就变成了未定义=，=||| 是我操作错误么。

**Comment by ichynul** [comment]
```php
exit('<script>var index = parent.layer.getFrameIndex(window.name);parent.layer.close(index);parent.toastr.success('操作成功')</script>');
```
这样可以吧

**Comment by Yesr00** [comment]
成功解决。感谢大佬。
