### ISSUE TITLE
laravel-admin1.7.3列表操作不支持打开新的tab页

### ISSUE THREAD

**Issue by woodzeng** [ichynul/iframe-tabs#52]
> v1.7.3版本对数据表格的行操作和批量操作进行了重构，数据的行操作重构为下拉菜单的形式

新版本点击编辑等按钮只能在原tab页打开，需要使用原按钮图标形式才可以
`'grid_action_class' => \Encore\Admin\Grid\Displayers\Actions::class,`

**Comment by ichynul** [comment]
最近太忙了，没太多时间弄，你可以试着修复一下提交pr

**Comment by ComeZC** [comment]
@woodzeng 我这边升级版本也是碰到了下拉菜单的行操作无法正确打开对应页面的问题，然后发现是那边渲染页面的一段js有问题，在那边提交了pr，[https://github.com/z-song/laravel-admin/pull/4671](url)，你可以参考下看是不是同一个问题。
