### ISSUE TITLE
swooletw/laravel-swoole

### ISSUE THREAD

**Issue by wen-gg** [ichynul/iframe-tabs#53]
你好，当我使用 swooletw/laravel-swoole 包时，使用不了此扩展

**Comment by ichynul** [comment]
我现在没有用`laravel-admin`这个框架了，没有时间研究了。
可能要修改一下`routes/web.php `的路由吧。

**Comment by wen-gg** [comment]
好的，我试试

**Comment by ichynul** [comment]
最新版本已修复此问题，升级到最新版，在扩展配置里面新加配置：`'web_in_cli' => false`
