### ISSUE TITLE
使用Laravels+Laravel-Admin以后有些问题。

### ISSUE THREAD

**Issue by Yesr00** [ichynul/iframe-tabs#54]
如题。集成swoole以后。插件的所有功能都不生效了。而且控制台不报错。求大佬解答。

**Comment by ichynul** [comment]
可能是因为`cli`模式的原因，我尝试做了一下调整，更新到最新版看看。

**Comment by Yesr00** [comment]
![image](https://user-images.githubusercontent.com/47804568/99892498-6bd63a00-2cb0-11eb-939d-912b4c7c718d.png)
点击其他页面iframes标签还是没有。更新完后iframes标签的功能依然不生效。但是点击页签的功能控制台出现报错。默认首页内容依旧是空白。

**Comment by Yesr00** [comment]
![image](https://user-images.githubusercontent.com/47804568/99892531-ab048b00-2cb0-11eb-83c2-d4a42b0144ab.png)

**Comment by ichynul** [comment]
在这个扩展的配置里面加了 `'web_in_cli' => true` 了吗

**Comment by Yesr00** [comment]
可以了。谢谢大佬~
