### ISSUE TITLE
5.5 Laravel 1.6 Laravel-admin Admin方法缺失

### ISSUE THREAD

**Issue by MTEzNjA4MA** [ichynul/iframe-tabs#6]
Exception message: Call to undefined method Encore\Admin\Admin::jQuery()
Exception message: Call to undefined method Encore\Admin\Admin::jQuery() (View: F:\wx_cloud\wx_cloud_manage\vendor\ichynul\iframe-tabs\resources\views\admin\index.blade.php)

同样还有一个调用了 Admin 里面 headerJs() 
这两个方法具体实现了什么呢  
谢谢啦

**Comment by ichynul** [comment]
可能是你用的Laravel-admin版本有点低，有些东西改变了。

**Comment by MTEzNjA4MA** [comment]
我用的是 1.6.0 应该是不会有这个问题

**Comment by ichynul** [comment]
变化还是大的，我弄的时候也没太注意这个问题。我研究一下看看尽量兼容一下低版本。

**Comment by MTEzNjA4MA** [comment]
1.6.10 不是最高吗  1.6.0 应该不会不兼容  你方便看下我说的这两个方法内容具体作用是什么吗

**Comment by ichynul** [comment]
[https://github.com/z-song/laravel-admin/blob/master/src/Traits/HasAssets.php](url)

**Comment by MTEzNjA4MA** [comment]
谢谢  辛苦啦

**Comment by ichynul** [comment]
已经做了调整，更新到最新版试试看
